- name: check tomcat9 is present or not if not install it
  hosts: all
  tasks:
      - block:
          - name: tomcat9 checkup
            service:
                    name: tomcat9
                    state: started
            register: a
          - name: debug module
            debug:
                    var: a
        rescue:
          - name: install
            apt:
                name: tomcat9
                state: present

