- name: check tomcat9 is present or not if not install it
  hosts: all
  tasks:
          - name: tomcat9 checkup
            service:
                    name: tomcat9
                    state: started
            register: result
            ignore_errors: true
          - name: debug module
            debug:
                    var: a
          - name: install
            apt:
                name: tomcat9
                state: present
            when: result is failed

