---
- name: mulitple loops
  hosts: all
  tasks:
        - name: install mulitple software
          apt:
                  name: "{{item.a}}"
                  state: "{{item.b}}"
                  update_cache: "{{item.c}}"
          with_items:
                  - {a: tree,b: present,c: no}
                  - {a: maven,b: absent,c: no}
                  - {a: git,b: latest,c: yes}
                  - {a: openjdk-8-jdk,b: absent,c: no}
            
...
