- name: set up of jekins and required softwares
  hosts: jenkinsserver
  tasks:
          - name: install required software
            apt:
                    name: "{{item.a}}"
                    state: present
                    update_cache: "{{item.b}}"
            with_items:
                    - {a: openjdk-8-jdk,b: yes}
                    - {a: git,b: no}
                    - {a: maven,b: no}
          - name: download jenkins war file
            get_url:
                    url: https://get.jenkins.io/war-stable/2.289.2/jenkins.war
                    dest: /tmp
- name: setup tomcat9 for other servers
  hosts: server
  tasks: 
        - name: install tomcat9
          apt:
                  name: "{{item.a}}"
                  state: present
                  update_cache: "{{item.b}}"
          with_items:
                  - {a: tomcat9,b: yes}
                  - {a: tomcat9-admin,b: yes}
        - name: copy the file 
          copy:
                  src: tomcat-users.xml
                  dest: /etc/tomcat9
          notify: restart tomcat9
  handlers:
          - name: restart tomcat9
            service:
                    name: tocmat9
                    state: restarted
