- name: error handling
  hosts: all
  tasks:
          - block: 
                - name: install tomcat8
                  apt:
                          name: tomcat8
                          state: present
                          update_cache: yesi
                          ignore_error: yes
                - name: display the msg
                  debug:
                          msg: "tomcat8 is  supported"     
            rescue:
                    - name: install tomcat9
                      apt: 
                        name: tomcat9
                        state: present
                        update_cache: yes
                    - name: display the msg
                      debug:
                              msg: "tomcat9 is  supported"
            always:
                   - name: display sme msg
                     debug:
                             msg: "apache installation is done"  
